### ISSUE TITLE
[Feature Request]: SSR

### ISSUE THREAD

**Issue by emregency** [OnurErtugral/react-image-comparison-slider#7]
Hi,

If I am not wrong, currently the library does not support Server Side Rendering. 

Is it possible to have it? 

Thanks for the library.

**Comment by OnurErtugral** [comment]
Hi, 

Thank you for opening this issue!

I have not done any SSR with React. So, I have no idea if this library is suitable for SSR. 

> Is it possible to have it?

Learning SSR is not a priority for me as of now. Therefore, I have no intention to work on this feature. However, PRs are welcome! If you want to work on it, I will be happy to merge your branch.

@emregency
